# Machine Learning (ipynb)

## Creating a 4x2 Matrix

In [11]:
import numpy
 
A = numpy.matrix([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])
A

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

## Accessing Item in Matrix

In [3]:
A[2, 1]

6

## Accessing Row Vector in Matrix

In [8]:
A[2, :]

matrix([[5, 6]])

## Accessing Col Vector in Matrix

In [9]:
A[:, 1]

matrix([[2],
        [4],
        [6],
        [8]])